# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        args: [--config=.flake8]
        stages: [commit]

      - id: hrflow_connectors_manifest
        name: hrflow_connectors_manifest
        entry: poetry run python -c 'from hrflow_connectors.v2 import __CONNECTORS__, hrflow_connectors_manifest as m; m(connectors=__CONNECTORS__)'
        language: system
        stages: [push]
        always_run: true
        pass_filenames: false

      - id: hrflow_connectors_docs
        name: hrflow_connectors_docs
        entry: poetry run python -c 'from hrflow_connectors import __CONNECTORS__ as __CONNECTORS__V1, generate_docs as docs_v1; from hrflow_connectors.v2 import __CONNECTORS__ as __CONNECTORS__V2, hrflow_connectors_docs as docs_v2; docs_v1(connectors=__CONNECTORS__V1); docs_v2(connectors=__CONNECTORS__V2)'
        language: system
        stages: [push]
        always_run: true
        pass_filenames: false
