actions:
  pull_job_list:
    - id: no_credentials
      origin_parameters:
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        board_key: $__HRFLOW_BOARD_KEY
      status: fatal
      reason: bad_origin_parameters

    - id: no_hrflow_board_key
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
      status: fatal
      reason: bad_target_parameters

    - id: valid_parameters
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        board_key: $__HRFLOW_BOARD_KEY
      status: success

    - id: invalid_boondmanager_credentials
      origin_parameters:
        client_key: bad_client_key
        client_token: bad_client_token
        user_token: bad_user_token
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        board_key: $__HRFLOW_BOARD_KEY
      status: fatal
      reason: read_failure

    - id: invalid_hrflow_api_secret
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__HRFLOW_API_USER
        board_key: $__HRFLOW_BOARD_KEY
      status: fatal
      reason: write_failure

    - id: filter_opportunity_states
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
        opportunity_states: "0"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        board_key: $__HRFLOW_BOARD_KEY
      status: success

  pull_profile_list:
    - id: no_credentials
      origin_parameters:
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
        only_edit_fields: []
      status: fatal
      reason: bad_origin_parameters

    - id: no_hrflow_source_key
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        only_edit_fields: []
      status: fatal
      reason: bad_target_parameters

    - id: valid_parameters
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
        only_edit_fields: []

    - id: filter_candidate_states
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
        candidate_states: "0,1,2,3,4,6,9"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
        only_edit_fields: []

    - id: invalid_boondmanager_credentials
      origin_parameters:
        client_key: bad_client_key
        client_token: bad_client_token
        user_token: bad_user_token
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
        only_edit_fields: []
      status: fatal
      reason: read_failure

    - id: invalid_hrflow_api_secret
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
        only_edit_fields: []
      status: fatal
      reason: write_failure

  pull_resume_attachment_list:
    - id: no_credentials
      origin_parameters:
        language: "fr"
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
      status: fatal
      reason: bad_origin_parameters

    - id: valid_parameters
      origin_parameters:
        client_key: $__CLIENT_KEY
        client_token: $__CLIENT_TOKEN
        user_token: $__USER_TOKEN
        language: "fr"
        limit: 5
      target_parameters:
        api_secret: $__HRFLOW_API_SECRET
        api_user: $__HRFLOW_API_USER
        source_key: $__HRFLOW_SOURCE_KEY
