actions:
  push_jobs:
    - id: valid_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
        job_key: $__JOB_KEY
      target_parameters:
        username: $__USERNAME
        password: $__PASSWORD
        api_key: $__API_KEY
        subdomain: $__SUBDOMAIN
      status: success
  
  catch_profile:
    - id: valid_parameters
      origin_parameters:
        profile: $__PROFILE
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
      status: success

        

  