actions:
  pull_jobs:
    - id: valid_parameters
      origin_parameters:
        api_key: $__API_KEY
        api_server: $__API_SERVER
        top: 1
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: success
    - id: not_x_smart_token
      origin_parameters:
        posting_status: PUBLIC
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: bad_origin_parameters
    - id: no_hrflow_board_key
      origin_parameters:
        api_key: $__API_KEY
        api_server: $__API_SERVER
        posting_status: PUBLIC
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
      status: fatal
      reason: bad_target_parameters
    - id: invalid_x_smart_token
      origin_parameters:
        api_key: bad_api_key
        api_server: $__API_SERVER
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: read_failure
    - id: invalid_hrflow_api_secret
      origin_parameters:
        api_key: $__API_KEY
        api_server: $__API_SERVER
        posting_status: PUBLIC
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: write_failure
  push_profile:
    - id: valid_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        profile_key: $__PROFILE_KEY       
      target_parameters:
        api_key: $__API_KEY
        api_server: $__API_SERVER
      status: success