/** 
 * Full Connector List & Translation Status
 * 
 * Total: 148 connectors
 * Completed: 1 (Bullhorn)
 * In Progress Generation: 147
 */

export const CONNECTOR_LIST_WITH_STATUS = [
  // ATS Systems (20+)
  { name: 'Abacusumantis', status: 'pending', files: 3 },
  { name: 'ADP Workforce Now', status: 'pending', files: 3 },
  { name: 'Ashby', status: 'pending', files: 3 },
  { name: 'Avature', status: 'pending', files: 3 },
  { name: 'Bamboo HR', status: 'pending', files: 3 },
  { name: 'Breezy HR', status: 'pending', files: 3 },
  { name: 'Bullhorn', status: 'complete', files: 3 },
  { name: 'Ceipal', status: 'pending', files: 3 },
  { name: 'Ceridian', status: 'pending', files: 3 },
  { name: 'ClayHR', status: 'pending', files: 3 },
  { name: 'Clockwork', status: 'pending', files: 3 },
  { name: 'Comeet', status: 'pending', files: 3 },
  { name: 'Cornerstone Ondemand', status: 'pending', files: 3 },
  { name: 'Cornerstone TalentLink', status: 'pending', files: 3 },
  { name: 'Crelate', status: 'pending', files: 3 },
  { name: 'eRecruiter', status: 'pending', files: 3 },
  { name: 'Factorial', status: 'pending', files: 3 },
  { name: 'Flatchr', status: 'pending', files: 3 },
  { name: 'Fountain', status: 'pending', files: 3 },
  { name: 'Freshteam', status: 'pending', files: 3 },
  { name: 'Glassdoor', status: 'pending', files: 3 },
  { name: 'Greenhouse', status: 'pending', files: 3 },
  { name: 'Guidecom', status: 'pending', files: 3 },
  { name: 'Harbour ATS', status: 'pending', files: 3 },
  { name: 'iCIMS', status: 'pending', files: 3 },
  { name: 'Jobscore', status: 'pending', files: 3 },
  { name: 'Kallidus Recruit', status: 'pending', files: 3 },
  { name: 'Leonardo', status: 'pending', files: 3 },
  { name: 'LeverHire', status: 'pending', files: 3 },
  { name: 'Milestone TMS', status: 'pending', files: 3 },
  { name: 'Oracle Recruiting', status: 'pending', files: 3 },
  { name: 'Peoplefirst', status: 'pending', files: 3 },
  { name: 'Pinpoint', status: 'pending', files: 3 },
  { name: 'Polymer', status: 'pending', files: 3 },
  { name: 'REC', status: 'pending', files: 3 },
  { name: 'Recruiter.com', status: 'pending', files: 3 },
  { name: 'Recruitee', status: 'pending', files: 3 },
  { name: 'Recruiters', status: 'pending', files: 3 },
  { name: 'Reedsy', status: 'pending', files: 3 },
  { name: 'Saga Selection', status: 'pending', files: 3 },
  { name: 'Seeqle', status: 'pending', files: 3 },
  { name: 'ShortlistMe', status: 'pending', files: 3 },
  { name: 'Staffing911', status: 'pending', files: 3 },
  { name: 'Successfactors', status: 'pending', files: 3 },
  { name: 'Talentdesk', status: 'pending', files: 3 },
  { name: 'Talentlms', status: 'pending', files: 3 },
  { name: 'Talentpool', status: 'pending', files: 3 },
  { name: 'Talentsmart', status: 'pending', files: 3 },
  { name: 'Taleap', status: 'pending', files: 3 },
  { name: 'Talentrizer', status: 'pending', files: 3 },
  { name: 'Taulontonline', status: 'pending', files: 3 },
  { name: 'TrustRadius', status: 'pending', files: 3 },
  { name: 'Umantis', status: 'pending', files: 3 },
  { name: 'Workable', status: 'pending', files: 3 },
  { name: 'Workday', status: 'pending', files: 3 },
  { name: 'Zap Talent', status: 'pending', files: 3 },
  { name: 'Zoho Recruit', status: 'pending', files: 3 },

  // Job Boards (30+)
  { name: 'Adzuna', status: 'pending', files: 3 },
  { name: 'ApecGroup', status: 'pending', files: 3 },
  { name: 'Bitecom', status: 'pending', files: 3 },
  { name: 'Broadbean', status: 'pending', files: 3 },
  { name: 'CadreEmploi', status: 'pending', files: 3 },
  { name: 'Careerjet', status: 'pending', files: 3 },
  { name: 'CareerBuilder', status: 'pending', files: 3 },
  { name: 'Carriereplus', status: 'pending', files: 3 },
  { name: 'Classifieds.com', status: 'pending', files: 3 },
  { name: 'Cornerjob', status: 'pending', files: 3 },
  { name: 'Digital Recruiters', status: 'pending', files: 3 },
  { name: 'Distrijob', status: 'pending', files: 3 },
  { name: 'D'Vinci', status: 'pending', files: 3 },
  { name: 'Eolia', status: 'pending', files: 3 },
  { name: 'Eploy', status: 'pending', files: 3 },
  { name: 'Engagelets', status: 'pending', files: 3 },
  { name: 'Engagement Jeunes', status: 'pending', files: 3 },
  { name: 'Fashionjobs', status: 'pending', files: 3 },
  { name: 'Figaro Classifieds', status: 'pending', files: 3 },
  { name: 'Freework', status: 'pending', files: 3 },
  { name: 'Goldenbees', status: 'pending', files: 3 },
  { name: 'Handicap Job', status: 'pending', files: 3 },
  { name: 'Heidijobs', status: 'pending', files: 3 },
  { name: 'Indeedbiz', status: 'pending', files: 3 },
  { name: 'Jobisjob', status: 'pending', files: 3 },
  { name: 'Jobvite', status: 'pending', files: 3 },
  { name: 'Jora', status: 'pending', files: 3 },
  { name: 'Indeed', status: 'pending', files: 3 },
  { name: 'Joblift', status: 'pending', files: 3 },
  { name: 'Jobtome', status: 'pending', files: 3 },
  { name: 'Jobsearch.com', status: 'pending', files: 3 },
  { name: 'Kimble', status: 'pending', files: 3 },
  { name: 'Laponi', status: 'pending', files: 3 },
  { name: 'Linkedin', status: 'pending', files: 3 },
  { name: 'Livetecs', status: 'pending', files: 3 },
  { name: 'Monster', status: 'pending', files: 3 },
  { name: 'MrJobz', status: 'pending', files: 3 },
  { name: 'Neuvoo', status: 'pending', files: 3 },
  { name: 'Nhance', status: 'pending', files: 3 },
  { name: 'Onlyfy', status: 'pending', files: 3 },
  { name: 'Otys', status: 'pending', files: 3 },
  { name: 'Peopleboard', status: 'pending', files: 3 },
  { name: 'Pole-emploi', status: 'pending', files: 3 },
  { name: 'Qapa', status: 'pending', files: 3 },
  { name: 'RhExperience', status: 'pending', files: 3 },
  { name: 'Savoirsplus', status: 'pending', files: 3 },
  { name: 'Seek', status: 'pending', files: 3 },
  { name: 'Staffsquared', status: 'pending', files: 3 },
  { name: 'Stepstone', status: 'pending', files: 3 },
  { name: 'Student Job', status: 'pending', files: 3 },
  { name: 'TalentClue', status: 'pending', files: 3 },
  { name: 'TalentDesk', status: 'pending', files: 3 },
  { name: 'Talentshare', status: 'pending', files: 3 },
  { name: 'Talevnt', status: 'pending', files: 3 },
  { name: 'Talipot', status: 'pending', files: 3 },
  { name: 'Team Lease', status: 'pending', files: 3 },
  { name: 'The Job App', status: 'pending', files: 3 },
  { name: 'TotalJobs', status: 'pending', files: 3 },
  { name: 'Tradeclassifieds', status: 'pending', files: 3 },
  { name: 'TradeKey', status: 'pending', files: 3 },
  { name: 'Tribepad', status: 'pending', files: 3 },
  { name: 'Trusted Jobs', status: 'pending', files: 3 },
  { name: 'UltimateStaffing', status: 'pending', files: 3 },
  { name: 'Viadeo', status: 'pending', files: 3 },
  { name: 'Vit Jobs', status: 'pending', files: 3 },
  { name: 'VivApps', status: 'pending', files: 3 },
  { name: 'Volunteerclick', status: 'pending', files: 3 },
  { name: 'Welobs', status: 'pending', files: 3 },
  { name: 'Welcome To The Jungle', status: 'pending', files: 3 },
  { name: 'Workavenue', status: 'pending', files: 3 },
  { name: 'Workfresh', status: 'pending', files: 3 },
  { name: 'Workingjobs', status: 'pending', files: 3 },
  { name: 'WorkIT', status: 'pending', files: 3 },
  { name: 'Yext', status: 'pending', files: 3 },
  { name: 'Yourjob', status: 'pending', files: 3 },
  { name: 'ZipRecruiter', status: 'pending', files: 3 },

  // CRM Systems
  { name: 'HubSpot', status: 'pending', files: 3 },
  { name: 'Salesforce', status: 'pending', files: 3 },
  { name: 'Pipedrive', status: 'pending', files: 3 },

  // Automation & Others
  { name: 'HrFlow', status: 'pending', files: 3 },
];

export function getTranslationStats() {
  const completed = CONNECTOR_LIST_WITH_STATUS.filter((c) => c.status === 'complete').length;
  const pending = CONNECTOR_LIST_WITH_STATUS.filter((c) => c.status === 'pending').length;
  const totalFiles = CONNECTOR_LIST_WITH_STATUS.reduce((sum, c) => sum + c.files, 0);

  return {
    totalConnectors: CONNECTOR_LIST_WITH_STATUS.length,
    completed,
    pending,
    completionPercentage: Math.round((completed / CONNECTOR_LIST_WITH_STATUS.length) * 100),
    totalFiles,
    estimatedFilesComplete: completed * 3 + 10, // 3 files per connector + core files
    estimatedFilesRemaining: pending * 3,
  };
}
