warehouse:
  PoleEmploiJobWarehouse:
    read:
      - parameters:
          access_token: $__ACCESS_TOKEN
actions:
  pull_jobs:
    - id: valid_parameters
      origin_parameters:
        access_token: $__ACCESS_TOKEN
        theme: "5"
        secteurActivite: "72"
        typeContrat: "CDI"
        natureContrat: "E1"
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: success
    - id: invalid_parameters
      origin_parameters:
        access_token: $__ACCESS_TOKEN
        codeROME: "K1304"
        appellation: "20003" #no such appellation code
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: bad_origin_parameters
    - id: invalid_parameter_type
      origin_parameters:
        access_token: $__ACCESS_TOKEN
        theme: 5
        secteurActivite: "72"
        typeContrat: "CDI"
        natureContrat: "E1"
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: bad_origin_parameters
    - id: no_access_token
      origin_parameters:
        motsCles: INFORMATIQUE
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: bad_origin_parameters
    - id: no_hrflow_board_key
      origin_parameters:
        access_token: $__ACCESS_TOKEN
        motsCles : Software
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
      status: fatal
      reason: bad_target_parameters
    - id: invalid_access_token
      origin_parameters:
        access_token: bad_access_token
        motsCles : Software
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: read_failure
    - id: invalid_hrflow_api_secret
      origin_parameters:
        access_token: $__ACCESS_TOKEN
        motsCles : Software
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal
      reason: write_failure
