warehouse:
  WaalaxyProfilesWarehouse:
    read:
      - parameters:
          profile: {
    "_id": "63579da9dc3ed5f5b5556725",
    "email": "",
    "company_linkedinUrl": "https://www.linkedin.com/company/hrflowai",
    "company_name": "HrFlow.ai",
    "connectedAt": "",
    "company_website": "https://hrflow.ai",
    "premium": "No",
    "prospectList": "Invitation Workflow",
    "firstName": "Léo",
    "jobSeeker": "No",
    "tags": "",
    "lastName": "FERRETTI",
    "linkedinUrl": "https://www.linkedin.com/in/léo-ferretti/",
    "dropcontactEmail": "",
    "emailReplied": "No",
    "occupation": "Étudiant(e) à EPITA: Ecole d'Ingénieurs en Informatique",
    "phoneNumbers": "",
    "emailSent": "No",
    "firstMessageAt": "",
    "location": "Carpentras  Provence-Alpes-Côte d'Azur  France",
    "messageReplied": "Yes",
    "messageSent": "No",
    "profileStatus": "pending",
    "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAADlFw4UBM68oBJlIWKiHPCaHfKv7nQwG-7o,NAME_SEARCH",
    "__typename": "FormattedProspect",
}
actions:
  trigger_view:
    - id: valid_parameters
      origin_parameters:
        profile: {
    "_id": "63579da9dc3ed5f5b5556725",
    "email": "",
    "company_linkedinUrl": "https://www.linkedin.com/company/hrflowai",
    "company_name": "HrFlow.ai",
    "connectedAt": "",
    "company_website": "https://hrflow.ai",
    "premium": "No",
    "prospectList": "Invitation Workflow",
    "firstName": "Léo",
    "jobSeeker": "No",
    "tags": "",
    "lastName": "FERRETTI",
    "linkedinUrl": "https://www.linkedin.com/in/léo-ferretti/",
    "dropcontactEmail": "",
    "emailReplied": "No",
    "occupation": "Étudiant(e) à EPITA: Ecole d'Ingénieurs en Informatique",
    "phoneNumbers": "",
    "emailSent": "No",
    "firstMessageAt": "",
    "location": "Carpentras  Provence-Alpes-Côte d'Azur  France",
    "messageReplied": "Yes",
    "messageSent": "No",
    "profileStatus": "pending",
    "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAADlFw4UBM68oBJlIWKiHPCaHfKv7nQwG-7o,NAME_SEARCH",
    "__typename": "FormattedProspect",
}
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        only_edit_fields: ["tags"]
      status: success
    - id: no_hrflow_source_key
      origin_parameters:
        profile: {
    "_id": "63579da9dc3ed5f5b5557625",
    "email": "",
    "company_linkedinUrl": "https://www.linkedin.com/company/hrflowai",
    "company_name": "HrFlow.ai",
    "connectedAt": "",
    "company_website": "https://hrflow.ai",
    "premium": "No",
    "prospectList": "Invitation Workflow",
    "firstName": "Léo",
    "jobSeeker": "No",
    "tags": "",
    "lastName": "FERRETTI",
    "linkedinUrl": "https://www.linkedin.com/in/léo-ferretti/",
    "dropcontactEmail": "",
    "emailReplied": "No",
    "occupation": "Étudiant(e) à EPITA: Ecole d'Ingénieurs en Informatique",
    "phoneNumbers": "",
    "emailSent": "No",
    "firstMessageAt": "",
    "location": "Carpentras  Provence-Alpes-Côte d'Azur  France",
    "messageReplied": "Yes",
    "messageSent": "No",
    "profileStatus": "pending",
    "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAADlFw4UBM68oBJlIWKiHPCaHfKv7nQwG-7o,NAME_SEARCH",
    "__typename": "FormattedProspect",
}
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        only_edit_fields: ["tags"]
      status: fatal
      reason: bad_target_parameters
    - id: invalid_hrflow_api_secret
      origin_parameters:
        profile: {
    "_id": "63579da9dc3ed5f5b5557625",
    "email": "",
    "company_linkedinUrl": "https://www.linkedin.com/company/hrflowai",
    "company_name": "HrFlow.ai",
    "connectedAt": "",
    "company_website": "https://hrflow.ai",
    "premium": "No",
    "prospectList": "Invitation Workflow",
    "firstName": "Léo",
    "jobSeeker": "No",
    "tags": "",
    "lastName": "FERRETTI",
    "linkedinUrl": "https://www.linkedin.com/in/léo-ferretti/",
    "dropcontactEmail": "",
    "emailReplied": "No",
    "occupation": "Étudiant(e) à EPITA: Ecole d'Ingénieurs en Informatique",
    "phoneNumbers": "",
    "emailSent": "No",
    "firstMessageAt": "",
    "location": "Carpentras  Provence-Alpes-Côte d'Azur  France",
    "messageReplied": "Yes",
    "messageSent": "No",
    "profileStatus": "pending",
    "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAADlFw4UBM68oBJlIWKiHPCaHfKv7nQwG-7o,NAME_SEARCH",
    "__typename": "FormattedProspect",
}
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        only_edit_fields: ["tags"]
      status: fatal
      reason: write_failure
  trigger_connexion:
    - id: valid_parameters
      origin_parameters:
        profile: {
  "_id": "6356515f55f4f3ecfa4e92e2",
  "email": "",
  "company_linkedinUrl": null,
  "company_name": "Freelance",
  "connectedAt": "",
  "company_website": null,
  "premium": "Yes",
  "prospectList": "Waalaxy (free to test)",
  "firstName": "Ferdinand Caoimhìn",
  "jobSeeker": "No",
  "tags": "",
  "lastName": "A.",
  "linkedinUrl": "https://www.linkedin.com/in/ferdinandaupetit/",
  "dropcontactEmail": "",
  "emailReplied": "No",
  "occupation": "Head of Growth",
  "phoneNumbers": "",
  "emailSent": "No",
  "firstMessageAt": "",
  "location": "France",
  "messageReplied": "No",
  "messageSent": "No",
  "profileStatus": "not_connected",
  "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAAAU7eFYBhIxQr-qMNRKHHTgVuyn1tZp41Ms,NAME_SEARCH",
  "__typename": "FormattedProspect"
}
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        only_edit_fields: ["tags"]
      status: success
    - id: no_hrflow_source_key
      origin_parameters:
        profile: {
  "_id": "6356515f55f4f3ecfa4e29e2",
  "email": "",
  "company_linkedinUrl": null,
  "company_name": "Freelance",
  "connectedAt": "",
  "company_website": null,
  "premium": "Yes",
  "prospectList": "Waalaxy (free to test)",
  "firstName": "Ferdinand Caoimhìn",
  "jobSeeker": "No",
  "tags": "",
  "lastName": "A.",
  "linkedinUrl": "https://www.linkedin.com/in/ferdinandaupetit/",
  "dropcontactEmail": "",
  "emailReplied": "No",
  "occupation": "Head of Growth",
  "phoneNumbers": "",
  "emailSent": "No",
  "firstMessageAt": "",
  "location": "France",
  "messageReplied": "No",
  "messageSent": "No",
  "profileStatus": "not_connected",
  "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAAAU7eFYBhIxQr-qMNRKHHTgVuyn1tZp41Ms,NAME_SEARCH",
  "__typename": "FormattedProspect"
}
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        only_edit_fields: ["tags"]
      status: fatal
      reason: bad_target_parameters

    - id: invalid_hrflow_api_secret
      origin_parameters:
        profile: {
  "_id": "6356515f55f4f3ecfa4e29e2",
  "email": "",
  "company_linkedinUrl": null,
  "company_name": "Freelance",
  "connectedAt": "",
  "company_website": null,
  "premium": "Yes",
  "prospectList": "Waalaxy (free to test)",
  "firstName": "Ferdinand Caoimhìn",
  "jobSeeker": "No",
  "tags": "",
  "lastName": "A.",
  "linkedinUrl": "https://www.linkedin.com/in/ferdinandaupetit/",
  "dropcontactEmail": "",
  "emailReplied": "No",
  "occupation": "Head of Growth",
  "phoneNumbers": "",
  "emailSent": "No",
  "firstMessageAt": "",
  "location": "France",
  "messageReplied": "No",
  "messageSent": "No",
  "profileStatus": "not_connected",
  "salesNavigatorUrl": "https://www.linkedin.com/sales/people/ACwAAAU7eFYBhIxQr-qMNRKHHTgVuyn1tZp41Ms,NAME_SEARCH",
  "__typename": "FormattedProspect"
}
      target_parameters:
        api_secret: bad_api_secret
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        only_edit_fields: ["tags"]
      status: fatal
      reason: write_failure