warehouse:
  SmartRecruitersJobWarehouse:
    pull:
      - parameters:
          x_smart_token: $__X_SMART_TOKEN
          posting_status: PUBLIC
actions:
  pull_jobs:
    - id: valid_parameters
      source_parameters:
        x_smart_token: $__X_SMART_TOKEN
        posting_status: PUBLIC
      destination_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      action_status: success
    - id: not_x_smart_token
      source_parameters:
        posting_status: PUBLIC
      destination_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      action_status: bad_source_parameters
    - id: no_hrflow_board_key
      source_parameters:
        x_smart_token: $__X_SMART_TOKEN
        posting_status: PUBLIC
      destination_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
      action_status: bad_destination_parameters
    - id: invalid_x_smart_token
      source_parameters:
        x_smart_token: bad_smart_token
        posting_status: PUBLIC
      destination_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      action_status: pulling_failure
    - id: invalid_hrflow_api_secret
      source_parameters:
        x_smart_token: $__X_SMART_TOKEN
        posting_status: PUBLIC
      destination_parameters:
        api_secret: bad_api_secret
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      action_status: pushing_failure
