actions:
  pull_job_list:
    - id: valid_parameters
      origin_parameters:
        digital_recruiters_token: $__DIGITAL_RECRUITERS_TOKEN
        digital_recruiters_environment_url:  $__DIGITAL_RECRUITERS_ENVIRONMENT_URL
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
    - id: bad target param
      origin_parameters:
        digital_recruiters_token: $__DIGITAL_RECRUITERS_TOKEN
        digital_recruiters_environment_url:  $__DIGITAL_RECRUITERS_ENVIRONMENT_URL
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: "123"
      status: fatal
    - id: bad origin param
      origin_parameters:
        digital_recruiters_token: "123"
        digital_recruiters_environment_url: "url"
      target_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        board_key: $__BOARD_KEY
      status: fatal

  push_profile:
    - id: valid_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        profile_key: $__PROFILE_KEY       
      
      target_parameters: 
        digital_recruiters_token: $__DIGITAL_RECRUITERS_TOKEN 
        digital_recruiters_environment_url: $__DIGITAL_RECRUITERS_ENVIRONMENT_URL
        job_reference: $__JOB_REFERENCE
        message: $__MESSAGE
      status: success
    - id: invalid_origin_parameters
      origin_parameters:
        api_secret: "123"
        api_user: "123"
        source_key: "123"
        profile_key: "123"       
      
      target_parameters:
        digital_recruiters_token: $__DIGITAL_RECRUITERS_TOKEN 
        digital_recruiters_environment_url: $__DIGITAL_RECRUITERS_ENVIRONMENT_URL
        job_reference: $__JOB_REFERENCE
        message: $__MESSAGE
      status: fatal

    - id: invalid_target_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        profile_key: $__PROFILE_KEY       
      
      target_parameters:
        digital_recruiters_token: true 
        digital_recruiters_environment_url: $__DIGITAL_RECRUITERS_ENVIRONMENT_URL
        job_reference: $__JOB_REFERENCE
        message: $__MESSAGE
      status: fatal
