from typing import Optional

from pydantic import BaseModel, Field


class CrosstalentJob(BaseModel):
    Name: str = Field("Undefined")
    Id: str = Field(..., description="ID d'enregistrement")
    createdDate: Optional[str]
    crtarecr__URL_of_the_form_on_job_offer__c: Optional[str] = Field(
        None, description="URL of the job"
    )
    crta__Location__Latitude__s: Optional[float] = Field(
        None, description="Geolocation latitude"
    )
    crta__Location__Longitude__s: Optional[float] = Field(
        None, description="Geolocation longitude"
    )
    Lieu__c: Optional[str] = Field(None, description="Address")
    crta__CT_City__c: Optional[str] = Field(None, description="City")
    crta__CT_Country__c: Optional[str] = Field(None, description="Country")
    crta__CT_Postal_code__c: Optional[str] = Field(None, description="Postal code")
    crta__Postal_Code__c: Optional[str] = Field(None, description="Postal code")
    crta__CT_Description__c: Optional[str] = Field(None, description="Job description")
    crta__CT_Benefices_attendus__c: Optional[str] = Field(
        None, description="Job benefits"
    )
    crta__CT_Description__c: Optional[str] = Field(None, description="Job description")
    crta__CT_Detail_motif_recours_CDD__c: Optional[str]
    crta__CT_Horaires_particuliers__c: Optional[str]
    crta__CT_Needed_skills__c: Optional[str]
    crta__CT_Other_contract_benefits__c: Optional[str]
    crta__CT_Other_salary_benefits__c: Optional[str]
    crta__CT_Remuneration_variable__c: Optional[str]
    crta__RC_Service__c: Optional[str]
    crtarecr__Personalised_header__c: Optional[str]
    crtarecr__Required_Profile__c: Optional[str]
    Profil_recherche__c: Optional[str]
    crtarecr__Language_1__c: Optional[str]
    crtarecr__Language_level_1__c: Optional[str]
    crtarecr__Language_2__c: Optional[str]
    crtarecr__Language_level_2__c: Optional[str]
    crtarecr__Language_3__c: Optional[str]
    crtarecr__Language_level_3__c: Optional[str]
    OwnerId: Optional[str]
    IsDeleted: Optional[bool]
    CurrencyIsoCode: Optional[str]
    RecordTypeId: Optional[str]
    CreatedById: Optional[str]
    LastModifiedDate: Optional[str]
    LastModifiedById: Optional[str]
    SystemModstamp: Optional[str]
    LastActivityDate: Optional[str]
    LastViewedDate: Optional[str]
    LastReferencedDate: Optional[str]
    crta__Etat__c: Optional[str]
    crta__CT_Avec_RTT__c: Optional[bool]
    crta__CT_Annee_budget__c: Optional[str]
    crta__CT_Contact_Person__c: Optional[str]
    crta__CT_Motif_recours_CDD__c: Optional[str]
    crta__CT_Nom_demandeur_DAR__c: Optional[str]
    crta__Contrainte__c: Optional[str]
    crta__Categorie__c: Optional[str]
    crta__CT_Organization_name__c: Optional[str]
    crta__Diffusion_de_l_offre__c: Optional[bool]
    crta__Origine_de_l_offre__c: Optional[str]
    crta__Email_du_recruteur__c: Optional[str]
    crta__Temps_de_travail_en_pourcentage__c: Optional[str]
    crta__Filiere__c: Optional[str]
    crta__CT_Date__c: Optional[str]
    crta__Contrat__c: Optional[str]
    crta__CT_Salary__c: Optional[str]
    crta__Date_max_du_positionnement__c: Optional[str]
    crta__CT_Nom_Responsable_hierarchique__c: Optional[str]
    crta__CT_Duration__c: Optional[str]
    crta__CT_Duree_Stage__c: Optional[str]
    crta__CT_Email_Manager__c: Optional[str]
    crta__CT_End_date__c: Optional[str]
    crta__CT_Modalite_attribution_remun_variable__c: Optional[str]
    crta__CT_Industry_of_activities__c: Optional[str]
    crta__CT_Date_debut_Contrat__c: Optional[str]
    crta__CT_Date_fin_Contrat__c: Optional[str]
    crta__CT_date_validation_DAR__c: Optional[str]
    crta__CT_Motif_CDI__c: Optional[str]
    crta__CT_Number_of_opened_positions__c: Optional[int]
    crta__CT_Prevu_au_budget__c: Optional[bool]
    crta__CT_Publiee_Site_web_externe__c: Optional[bool]
    crta__CT_Scope__c: Optional[bool]
    crta__CT_Entrprise_Postal_code__c: Optional[str]
    crta__Date_limite_de_reponse__c: Optional[str]
    crta__Duree_ouverture_mois__c: Optional[int]
    crta__Etat__c: Optional[str]
    crta__Status__c: Optional[str]
    crtarecr__Archived__c: Optional[bool]
    crtarecr__Contract_type__c: Optional[str]
    crtarecr__Published_on_Jobboards__c: Optional[bool]
    crtarecr__Published_on_Website__c: Optional[bool]
    crtarecr__Recruitment_Request_Date__c: Optional[str]
    crtarecr__Recruitment_request_status__c: Optional[str]
    M_tier__c: Optional[str]
    Famille_de_m_tier__c: Optional[str]
    Sourcing_Auto__c: Optional[bool]
    Disponibilit_imm_diate__c: Optional[bool]
    Date_de_d_but__c: Optional[str]
    Fourchette_de_salaire__c: Optional[str]
    Mobilit_R_gion__c: Optional[str]
    Entit_juridique__c: Optional[str]
    Compte_de_rattachement__c: Optional[str]
    Site_de_diffusion_de_l_offre__c: Optional[str]
    Mobilit_Pays__c: Optional[str]
    Position__c: Optional[str]
    Mobilit_R_gion__c: Optional[str]
    Pays__c: Optional[str]
    Mots_Clefs__c: Optional[str]
    Emploi_Type__c: Optional[str]
    Niveau_d_exp_rience_attendu__c: Optional[str]
    Domaine_d_activite__c: Optional[str]
    Secteur_d_activite__c: Optional[str]
    Date_de_fin__c: Optional[str]
    crtarecr__BU1__c: Optional[str]
    crtarecr__BU2__c: Optional[str]
    crtarecr__Contractual_status__c: Optional[str]
    crtarecr__Employment_start_date__c: Optional[str]
    crtarecr__End_date_of_Intranet_Site_publication__c: Optional[str]
    crtarecr__End_date_of_Jobboard_publication__c: Optional[str]
    crtarecr__End_date_of_Website_publication__c: Optional[str]
    crtarecr__Envisaged_annual_gross_remuneration__c: Optional[str]
    crtarecr__HR_Function__c: Optional[str]
    crtarecr__Max_salary__c: Optional[int]
    crtarecr__Max_term_months__c: Optional[int]
    crtarecr__Min_salary__c: Optional[int]
    crtarecr__Min_term_months__c: Optional[int]
    crtarecr__Period__c: Optional[str]
    crtarecr__Recruiter_Firstname__c: Optional[str]
    crtarecr__Recruiter_Lastname__c: Optional[str]
    crtarecr__Reference__c: Optional[str]
    crtarecr__Required_Experience_Level__c: Optional[str]
    crtarecr__Required_diploma_level__c: Optional[str]
    crtarecr__Start_date_of_Intranet_Site_publication__c: Optional[str]
    crtarecr__Start_date_of_Jobboard_publication__c: Optional[str]
    crtarecr__Start_date_of_Website_publication__c: Optional[str]
    crtarecr__Type_of_employment__c: Optional[str]
    crtarecr__Weekly_Working_Time_in_hours__c: Optional[int]
    crta__CT_Designation__c: Optional[str]
    crta__Location__c: Optional[dict]
    crta__Nb_positionnements__c: Optional[int]
    crta__Texte_statut__c: Optional[str]
    crta__Valeur_statut__c: Optional[int]
    crtarecr__Link_of_the_form_on_job_offer__c: Optional[str]
    crtarecr__Nb_of_applications_still_to_be_processed__c: Optional[int]
    Besoin_client__c: Optional[str]
    crta__Entite__c: Optional[str]
