actions:
  push_profile:
    - id: valid_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        profile_key: $__PROFILE_KEY
      target_parameters:
        username: $__USERNAME
        password: $__PASSWORD
        client_id: $__CLIENT_ID
        client_secret: $__CLIENT_SECRET
      status: success  
    - id: invalid_destination_parameters
      origin_parameters:
        api_secret: $__API_SECRET
        api_user: $__API_USER
        source_key: $__SOURCE_KEY
        profile_key: $__PROFILE_KEY
      target_parameters:
        username: $__USERNAME
        password: $__PASSWORD
        client_id: not_an_id
        client_secret: $__CLIENT_SECRET
      status: fatal